[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
# base =

primaryColor="#1f2630"
backgroundColor="#1f2630"
secondaryBackgroundColor="#31333F"
textColor="#fafafa"
font="sans serif"