[theme]
primaryColor="#ff6361"
backgroundColor="#003f5c"
#secondaryBackgroundColor="#58508d"
secondaryBackgroundColor="#2f4b7c"
textColor="#ffa600"
font="sans serif"


#primaryColor="#ff6361"
#backgroundColor="#115f9a"
#secondaryBackgroundColor="#58508d"
#textColor="#ffa600"
#font="sans serif"